export { default as Footer } from './Footer/Footer.jsx'
export { default as Navbar } from './Navbar/Navbar.jsx'
export { default as Section } from './Section/Section.jsx'
export { default as MouseProfiler } from './MouseProfiler/MouseProfiler'
export { default as ErrorsCounter } from './ErrorsCounter/ErrorsCounter'